#!/bin/sh
set -euf

##
# This script deletes log files that are created by various kinds of log file rotations.
#
# Syntax:
#
#     $ rm-rotated-files [dir]
#
# Example to process the current directory and all subdirectories:
#
#     $ rm-rotated-files
#
# Example to process a specific directory:
#
#     $ rm-rotated-files /var/log
#
#
# ## Which files?
#
# Compressed files:
#
#   * Files with extensions that are known to be compressed or archived.
#
#   * Examples: .bz2, .bzip, .gz, .tar, .tgz, .zip, .7zip
#
#   * See `rm-compressed-files` for complete info.
#
#
# Sidelined files:
#
#   * Files with extensions that are typically for old files.
#
#   * Examples: .bak, .old, .tmp
#
#   * See `rm-sidelined-files` for complete info.
#
#
# Numbered files:
#
#   * Files with names that end in a separator then number:
#
#   * Examples: foo.1, foo-2, foo_3, etc.
#
#  * See `rm-numbered-files` for complete info.
#
#
# Datestamped files:
#
#   * Files with names that end in a separator then ISO date.
#
#   * Examples: foo-2017-12-31, foo_2017_12_31, etc.
#
#  * See `rm-datestamped-files` for complete info.
#
#
# ## Compatibility notes
#
# We prefer to be more compatible rather than system-specific.
#
#   * To delete files, we prefer `-exec rm` vs. `-delete`.
#     The former is more compatible, the latter is faster.
#
#   * To name match, we prefer using `-name` vs. `-iname`.
#     This means we need to match on upper case and lower case.
#
#   * To regex match, we prefer patterns to be basic vs. extended.
#     The former is more compatible, the latter is more modern.
#
#   * We prefer POSIX code vs. shell-specific code.
#
#   * We prefer the code to be more DAMP than DRY.
#     For example, the code has separate name matching
#     for `.bz` and `.bz2`, even though we could combine these.
#
#
# ## Tracking
#
#   * Command: rm-rotated-files
#   * Website: http://sixarm.com/rm-rotated-files
#   * Cloning: https://github.com/sixarm/rm-rotated-files
#   * Version: 4.1.1
#   * Created: 2013-12-09
#   * Updated: 2019-09-08
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
#   * Tracker: 0f5f883770a0a2e85c7ec9a0c8296402
##

find "${1:-.}" \
     -type f \
     \( \
     -name "*.[Bb][Zz]" -o \
     -name "*.[Bb][Zz]2" -o \
     -name "*.[Bb][Zz][Ii][Pp]" -o \
     -name "*.[Gg][Zz]" -o \
     -name "*.[Tt][Aa][Rr]" -o \
     -name "*.[Tt][Aa][Rr].[LlXx][Zz]" -o \
     -name "*.[Tt][Gg][Zz]" -o \
     -name "*.[Zz][Ii][Pp]" -o \
     -name "*.7[Zz][Ii][Pp]" -o \
     -name "*.[Bb][Aa][Kk]" -o \
     -name "*.[Bb][Aa][Ck][Kk]" -o \
     -name "*.[Bb][Aa][Ck][Kk][Uu][Pp]" -o \
     -name "*.[Oo][Ll][Dd]" -o \
     -name "*.[Tt][Mm][Pp]" -o \
     -name "*.[Tt][Em][Mm][Pp]" -o \
     -name "*.[Tt][Em][Mm][Pp][Oo][Rr][Aa][Rr][Yy]" -o \
     -regex ".*[-\.][0123456789][0123456789]*" -o \
     -regex ".*[-_\.][0123456789][0123456789][0123456789][0123456789][-_\.][0123456789][0123456789][-_\.][0123456789][0123456789]" \) \
     -exec rm {} \;
